# permissions for end users to view awssecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: awssecret-viewer-role
rules:
- apiGroups:
  - mychart.my-chart.io
  resources:
  - awssecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mychart.my-chart.io
  resources:
  - awssecrets/status
  verbs:
  - get
