
name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build Docker image
        run: |
          commitid=$( echo ${{ github.sha }} | cut -c 1-6 )
          export commitid=$commitid
          docker build -t ghcr.io/${{ github.repository }}/operator:$commitid .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/operator:$commitid
